// http://jsfiddle.net/sturtevant/AZFvQ/
var monsterList = [
	{"name":"Aarakocra","size":"Medium","type":"Humanoid","tags":"Aarakocra","CR":"1/4","alignment":"neutral good","page":"MM 12"},
	{"name":"Aboleth","size":"Large","type":"Aberration","tags":"","CR":"10","alignment":"lawful evil","page":"MM 13"},
	{"name":"Deva","size":"Medium","type":"Celestial","tags":"Angel","CR":"10","alignment":"lawful good","page":"MM 16"},
	{"name":"Planetar","size":"Large","type":"Celestial","tags":"Angel","CR":"16","alignment":"lawful good","page":"MM 17"},
	{"name":"Solar","size":"Large","type":"Celestial","tags":"Angel","CR":"21","alignment":"lawful good","page":"MM 18"},
	{"name":"Animated Armor","size":"Medium","type":"Construct","tags":"","CR":"1","alignment":"unaligned","page":"MM 19"},
	{"name":"Flying Sword","size":"Small","type":"Construct","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 20"},
	{"name":"Rug of Smothering","size":"Large","type":"Construct","tags":"","CR":"2","alignment":"unaligned","page":"MM 20"},
	{"name":"Ankheg","size":"Large","type":"Monstrosity","tags":"","CR":"2","alignment":"unaligned","page":"MM 21"},
	{"name":"Azer","size":"Medium","type":"Elemental","tags":"","CR":"2","alignment":"lawful evil","page":"MM 22"},
	{"name":"Banshee","size":"Medium","type":"Undead","tags":"","CR":"4","alignment":"chaotic evil","page":"MM 23"},
	{"name":"Basilisk","size":"Medium","type":"Monstrosity","tags":"","CR":"3","alignment":"unaligned","page":"MM 24"},
	{"name":"Behir","size":"Huge","type":"Monstrosity","tags":"","CR":"11","alignment":"neutral evil","page":"MM 25"},
	{"name":"Beholder","size":"Large","type":"Aberration","tags":"","CR":"13","alignment":"lawful evil","page":"MM 28"},
	{"name":"Death Tyrant","size":"Large","type":"Undead","tags":"","CR":"14","alignment":"lawful evil","page":"MM 29"},
	{"name":"Spectator","size":"Medium","type":"Aberration","tags":"","CR":"3","alignment":"lawful neutral","page":"MM 30"},
	{"name":"Needle Blight","size":"Medium","type":"Plant","tags":"","CR":"1/4","alignment":"neutral evil","page":"MM 32"},
	{"name":"Twig Blight","size":"Small","type":"Plant","tags":"","CR":"1/8","alignment":"neutral evil","page":"MM 32"},
	{"name":"Vine Blight","size":"Medium","type":"Plant","tags":"","CR":"1/2","alignment":"neutral evil","page":"MM 32"},
	{"name":"Bugbear","size":"Medium","type":"Humanoid","tags":"Goblinoid","CR":"1","alignment":"chaotic evil","page":"MM 33"},
	{"name":"Bugbear Chief","size":"Medium","type":"Humanoid","tags":"Goblinoid","CR":"3","alignment":"chaotic evil","page":"MM 33"},
	{"name":"Bulette","size":"Large","type":"Monstrosity","tags":"","CR":"5","alignment":"unaligned","page":"MM 34"},
	{"name":"Bullywug","size":"Medium","type":"Humanoid","tags":"Bullywug","CR":"1/4","alignment":"neutral evil","page":"MM 35"},
	{"name":"Cambion","size":"Medium","type":"Fiend","tags":"","CR":"5","alignment":"any evil","page":"MM 36"},
	{"name":"Carrion Crawler","size":"Large","type":"Monstrosity","tags":"","CR":"2","alignment":"unaligned","page":"MM 37"},
	{"name":"Centaur","size":"Large","type":"Monstrosity","tags":"","CR":"2","alignment":"neutral good","page":"MM 38"},
	{"name":"Chimera","size":"Large","type":"Monstrosity","tags":"","CR":"6","alignment":"chaotic evil","page":"MM 39"},
	{"name":"Chuul","size":"Large","type":"Aberration","tags":"","CR":"4","alignment":"chaotic evil","page":"MM 40"},
	{"name":"Cloaker","size":"Large","type":"Aberration","tags":"","CR":"8","alignment":"chaotic neutral","page":"MM 41"},
	{"name":"Cockatrice","size":"Small","type":"Monstrosity","tags":"","CR":"1/2","alignment":"unaligned","page":"MM 42"},
	{"name":"Couatl","size":"Medium","type":"Celestial","tags":"","CR":"4","alignment":"lawful good","page":"MM 43"},
	{"name":"Crawling Claw","size":"Tiny","type":"Undead","tags":"","CR":"0","alignment":"neutral evil","page":"MM 44"},
	{"name":"Cyclops","size":"Huge","type":"Giant","tags":"","CR":"6","alignment":"chaotic neutral","page":"MM 45"},
	{"name":"Darkmantle","size":"Small","type":"Monstrosity","tags":"","CR":"1/2","alignment":"unaligned","page":"MM 46"},
	{"name":"Death Knight","size":"Medium","type":"Undead","tags":"","CR":"17","alignment":"chaotic evil","page":"MM 47"},
	{"name":"Demilich","size":"Tiny","type":"Undead","tags":"","CR":"18","alignment":"neutral evil","page":"MM 48"},
	{"name":"Balor","size":"Huge","type":"Fiend","tags":"Demon","CR":"19","alignment":"chaotic evil","page":"MM 55"},
	{"name":"Barlgura","size":"Large","type":"Fiend","tags":"Demon","CR":"5","alignment":"chaotic evil","page":"MM 56"},
	{"name":"Chasme","size":"Large","type":"Fiend","tags":"Demon","CR":"6","alignment":"chaotic evil","page":"MM 57"},
	{"name":"Dretch","size":"Small","type":"Fiend","tags":"Demon","CR":"1/4","alignment":"chaotic evil","page":"MM 57"},
	{"name":"Glabrezu","size":"Large","type":"Fiend","tags":"Demon","CR":"9","alignment":"chaotic evil","page":"MM 58"},
	{"name":"Goristro","size":"Huge","type":"Fiend","tags":"Demon","CR":"17","alignment":"chaotic evil","page":"MM 59"},
	{"name":"Hezrou","size":"Large","type":"Fiend","tags":"Demon","CR":"8","alignment":"chaotic evil","page":"MM 60"},
	{"name":"Manes","size":"Small","type":"Fiend","tags":"Demon","CR":"1/8","alignment":"chaotic evil","page":"MM 60"},
	{"name":"Marilith","size":"Large","type":"Fiend","tags":"Demon","CR":"16","alignment":"chaotic evil","page":"MM 61"},
	{"name":"Nalfeshnee","size":"Large","type":"Fiend","tags":"Demon","CR":"13","alignment":"chaotic evil","page":"MM 62"},
	{"name":"Quasit","size":"Tiny","type":"Fiend","tags":"Demon, Shapechanger","CR":"1","alignment":"chaotic evil","page":"MM 63"},
	{"name":"Shadow Demon","size":"Medium","type":"Fiend","tags":"Demon","CR":"4","alignment":"chaotic evil","page":"MM 64"},
	{"name":"Vrock","size":"Large","type":"Fiend","tags":"Demon","CR":"6","alignment":"chaotic evil","page":"MM 64"},
	{"name":"Yochlol","size":"Medium","type":"Fiend","tags":"Demon, Shapechanger","CR":"10","alignment":"chaotic evil","page":"MM 65"},
	{"name":"Barbed Devil","size":"Medium","type":"Fiend","tags":"Devil","CR":"5","alignment":"lawful evil","page":"MM 70"},
	{"name":"Bearded Devil","size":"Medium","type":"Fiend","tags":"Devil","CR":"3","alignment":"lawful evil","page":"MM 70"},
	{"name":"Bone Devil","size":"Large","type":"Fiend","tags":"Devil","CR":"9","alignment":"lawful evil","page":"MM 71"},
	{"name":"Chain Devil","size":"Medium","type":"Fiend","tags":"Devil","CR":"8","alignment":"lawful evil","page":"MM 72"},
	{"name":"Erinyes","size":"Medium","type":"Fiend","tags":"Devil","CR":"12","alignment":"lawful evil","page":"MM 73"},
	{"name":"Horned Devil","size":"Large","type":"Fiend","tags":"Demon","CR":"11","alignment":"lawful evil","page":"MM 74"},
	{"name":"Ice Devil","size":"Large","type":"Fiend","tags":"Devil","CR":"14","alignment":"lawful evil","page":"MM 75"},
	{"name":"Imp","size":"Tiny","type":"Fiend","tags":"Devil","CR":"1","alignment":"lawful evil","page":"MM 76"},
	{"name":"Lemure","size":"Medium","type":"Fiend","tags":"Devil","CR":"0","alignment":"lawful evil","page":"MM 76"},
	{"name":"Pit Fiend","size":"Large","type":"Fiend","tags":"Devil","CR":"20","alignment":"lawful evil","page":"MM 77"},
	{"name":"Spined Devil","size":"Small","type":"Fiend","tags":"Devil","CR":"2","alignment":"lawful evil","page":"MM 78"},
	{"name":"Allosaurus","size":"Large","type":"Beast","tags":"Dinosaur","CR":"2","alignment":"unaligned","page":"MM 79"},
	{"name":"Ankylosaurus","size":"Huge","type":"Beast","tags":"Dinosaur","CR":"3","alignment":"unaligned","page":"MM 79"},
	{"name":"Plesiosaurus","size":"Large","type":"Beast","tags":"Dinosaur","CR":"2","alignment":"unaligned","page":"MM 80"},
	{"name":"Pteranodon","size":"Medium","type":"Beast","tags":"Dinosaur","CR":"1/4","alignment":"unaligned","page":"MM 80"},
	{"name":"Triceratops","size":"Huge","type":"Beast","tags":"Dinosaur","CR":"5","alignment":"unaligned","page":"MM 80"},
	{"name":"Tyrannosaurus Rex","size":"Huge","type":"Beast","tags":"Dinosaur","CR":"8","alignment":"unaligned","page":"MM 80"},
	{"name":"Displacer Beast","size":"Large","type":"Monstrosity","tags":"","CR":"3","alignment":"lawful evil","page":"MM 81"},
	{"name":"Doppelganger","size":"Medium","type":"Monstrosity","tags":"Shapechanger","CR":"3","alignment":"true neutral","page":"MM 82"},
	{"name":"Dracolich","size":"Huge","type":"Undead","tags":"","CR":"17","alignment":"lawful evil","page":"MM 84"},
	{"name":"Shadow Dragon","size":"Large","type":"Dragon","tags":"","CR":"13","alignment":"chaotic evil","page":"MM 85"},
	{"name":"Black Dragon, Ancient","size":"Gargantuan","type":"Dragon","tags":"","CR":"21","alignment":"chaotic evil","page":"MM 87"},
	{"name":"Black Dragon, Adult","size":"Huge","type":"Dragon","tags":"","CR":"14","alignment":"chaotic evil","page":"MM 88"},
	{"name":"Black Dragon, Wyrmling","size":"Medium","type":"Dragon","tags":"","CR":"2","alignment":"chaotic evil","page":"MM 88"},
	{"name":"Black Dragon, Young","size":"Large","type":"Dragon","tags":"","CR":"7","alignment":"chaotic evil","page":"MM 88"},
	{"name":"Blue Dragon, Ancient","size":"Gargantuan","type":"Dragon","tags":"","CR":"23","alignment":"lawful evil","page":"MM 90"},
	{"name":"Blue Dragon, Adult","size":"Huge","type":"Dragon","tags":"","CR":"16","alignment":"lawful evil","page":"MM 91"},
	{"name":"Blue Dragon, Wyrmling","size":"Medium","type":"Dragon","tags":"","CR":"3","alignment":"lawful evil","page":"MM 91"},
	{"name":"Blue Dragon, Young","size":"Large","type":"Dragon","tags":"","CR":"9","alignment":"lawful evil","page":"MM 91"},
	{"name":"Green Dragon, Ancient","size":"Gargantuan","type":"Dragon","tags":"","CR":"22","alignment":"lawful evil","page":"MM 93"},
	{"name":"Green Dragon, Adult","size":"Huge","type":"Dragon","tags":"","CR":"15","alignment":"lawful evil","page":"MM 94"},
	{"name":"Green Dragon, Young","size":"Medium","type":"Dragon","tags":"","CR":"8","alignment":"lawful evil","page":"MM 94"},
	{"name":"Green Dragon, Wyrmling","size":"Large","type":"Dragon","tags":"","CR":"2","alignment":"lawful evil","page":"MM 95"},
	{"name":"Red Dragon, Ancient","size":"Gargantuan","type":"Dragon","tags":"","CR":"24","alignment":"chaotic evil","page":"MM 97"},
	{"name":"Red Dragon, Adult","size":"Huge","type":"Dragon","tags":"","CR":"17","alignment":"chaotic evil","page":"MM 98"},
	{"name":"Red Dragon, Wyrmling","size":"Medium","type":"Dragon","tags":"","CR":"4","alignment":"chaotic evil","page":"MM 98"},
	{"name":"Red Dragon, Young","size":"Large","type":"Dragon","tags":"","CR":"10","alignment":"chaotic evil","page":"MM 98"},
	{"name":"White Dragon, Ancient","size":"Gargantuan","type":"Dragon","tags":"","CR":"20","alignment":"chaotic evil","page":"MM 100"},
	{"name":"White Dragon, Adult","size":"Huge","type":"Dragon","tags":"","CR":"13","alignment":"chaotic evil","page":"MM 101"},
	{"name":"White Dragon, Young","size":"Medium","type":"Dragon","tags":"","CR":"6","alignment":"chaotic evil","page":"MM 101"},
	{"name":"White Dragon, Wyrmling","size":"Large","type":"Dragon","tags":"","CR":"2","alignment":"chaotic evil","page":"MM 102"},
	{"name":"Brass Dragon, Ancient","size":"Gargantuan","type":"Dragon","tags":"","CR":"20","alignment":"chaotic good","page":"MM 104"},
	{"name":"Brass Dragon, Adult","size":"Huge","type":"Dragon","tags":"","CR":"13","alignment":"chaotic good","page":"MM 105"},
	{"name":"Brass Dragon, Young","size":"Medium","type":"Dragon","tags":"","CR":"6","alignment":"chaotic good","page":"MM 105"},
	{"name":"Brass Dragon, Wyrmling","size":"Large","type":"Dragon","tags":"","CR":"1","alignment":"chaotic good","page":"MM 106"},
	{"name":"Bronze Dragon, Ancient","size":"Gargantuan","type":"Dragon","tags":"","CR":"22","alignment":"lawful good","page":"MM 107"},
	{"name":"Bronze Dragon, Adult","size":"Huge","type":"Dragon","tags":"","CR":"15","alignment":"lawful good","page":"MM 108"},
	{"name":"Bronze Dragon, Young","size":"Medium","type":"Dragon","tags":"","CR":"8","alignment":"lawful good","page":"MM 108"},
	{"name":"Bronze Dragon, Wyrmling","size":"Large","type":"Dragon","tags":"","CR":"2","alignment":"lawful good","page":"MM 109"},
	{"name":"Copper Dragon, Ancient","size":"Gargantuan","type":"Dragon","tags":"","CR":"21","alignment":"chaotic good","page":"MM 110"},
	{"name":"Copper Dragon, Adult","size":"Huge","type":"Dragon","tags":"","CR":"14","alignment":"chaotic good","page":"MM 111"},
	{"name":"Copper Dragon, Young","size":"Medium","type":"Dragon","tags":"","CR":"7","alignment":"chaotic good","page":"MM 111"},
	{"name":"Copper Dragon, Wyrmling","size":"Large","type":"Dragon","tags":"","CR":"1","alignment":"chaotic good","page":"MM 112"},
	{"name":"Gold Dragon, Ancient","size":"Gargantuan","type":"Dragon","tags":"","CR":"24","alignment":"lawful good","page":"MM 113"},
	{"name":"Gold Dragon, Adult","size":"Huge","type":"Dragon","tags":"","CR":"17","alignment":"lawful good","page":"MM 114"},
	{"name":"Gold Dragon, Wyrmling","size":"Medium","type":"Dragon","tags":"","CR":"3","alignment":"lawful good","page":"MM 115"},
	{"name":"Gold Dragon, Young","size":"Large","type":"Dragon","tags":"","CR":"10","alignment":"lawful good","page":"MM 115"},
	{"name":"Silver Dragon, Ancient","size":"Gargantuan","type":"Dragon","tags":"","CR":"23","alignment":"lawful good","page":"MM 116"},
	{"name":"Silver Dragon, Adult","size":"Huge","type":"Dragon","tags":"","CR":"16","alignment":"lawful good","page":"MM 117"},
	{"name":"Silver Dragon, Wyrmling","size":"Medium","type":"Dragon","tags":"","CR":"2","alignment":"lawful good","page":"MM 118"},
	{"name":"Silver Dragon, Young","size":"Large","type":"Dragon","tags":"","CR":"9","alignment":"lawful good","page":"MM 118"},
	{"name":"Dragon Turtle","size":"Gargantuan","type":"Dragon","tags":"","CR":"17","alignment":"unaligned","page":"MM 119"},
	{"name":"Drider","size":"Large","type":"Monstrosity","tags":"","CR":"6","alignment":"chaotic evil","page":"MM 120"},
	{"name":"Dryad","size":"Medium","type":"Fey","tags":"","CR":"1","alignment":"true neutral","page":"MM 121"},
	{"name":"Duergar","size":"Medium","type":"Humanoid","tags":"Dwarf","CR":"1","alignment":"lawful evil","page":"MM 122"},
	{"name":"Air Elemental","size":"Large","type":"Elemental","tags":"","CR":"5","alignment":"true neutral","page":"MM 124"},
	{"name":"Earth Elemental","size":"Large","type":"Elemental","tags":"","CR":"5","alignment":"true neutral","page":"MM 124"},
	{"name":"Fire Elemental","size":"Large","type":"Elemental","tags":"","CR":"5","alignment":"true neutral","page":"MM 125"},
	{"name":"Water Elemental","size":"Large","type":"Elemental","tags":"","CR":"5","alignment":"true neutral","page":"MM 125"},
	{"name":"Drow","size":"Medium","type":"Humanoid","tags":"Elf","CR":"1/4","alignment":"neutral evil","page":"MM 128"},
	{"name":"Drow Elite Warrior","size":"Medium","type":"Humanoid","tags":"Elf","CR":"5","alignment":"neutral evil","page":"MM 128"},
	{"name":"Drow Mage","size":"Medium","type":"Humanoid","tags":"Elf","CR":"7","alignment":"neutral evil","page":"MM 129"},
	{"name":"Drow Priestess of Lolth","size":"Medium","type":"Humanoid","tags":"Elf","CR":"8","alignment":"neutral evil","page":"MM 129"},
	{"name":"Empyrean","size":"Huge","type":"Celestial","tags":"Titan","CR":"23","alignment":"chaotic good","page":"MM 130"},
	{"name":"Empyrean","size":"Huge","type":"Celestial","tags":"Titan","CR":"23","alignment":"neutral evil","page":"MM 130"},
	{"name":"Ettercap","size":"Medium","type":"Monstrosity","tags":"","CR":"2","alignment":"neutral evil","page":"MM 131"},
	{"name":"Ettin","size":"Large","type":"Giant","tags":"","CR":"4","alignment":"chaotic evil","page":"MM 132"},
	{"name":"Faerie Dragon","size":"Tiny","type":"Dragon","tags":"","CR":"1","alignment":"chaotic good","page":"MM 133"},
	{"name":"Faerie Dragon","size":"Tiny","type":"Dragon","tags":"","CR":"2","alignment":"chaotic good","page":"MM 133"},
	{"name":"Flameskull","size":"Tiny","type":"Undead","tags":"","CR":"4","alignment":"neutral evil","page":"MM 134"},
	{"name":"Flumph","size":"Small","type":"Aberration","tags":"","CR":"1/8","alignment":"lawful good","page":"MM 135"},
	{"name":"Fomorian","size":"Huge","type":"Giant","tags":"","CR":"8","alignment":"chaotic evil","page":"MM 136"},
	{"name":"Gas Spore","size":"Large","type":"Plant","tags":"","CR":"1/2","alignment":"unaligned","page":"MM 138"},
	{"name":"Shrieker","size":"Medium","type":"Plant","tags":"","CR":"0","alignment":"unaligned","page":"MM 138"},
	{"name":"Violet Fungus","size":"Medium","type":"Plant","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 138"},
	{"name":"Galeb Duhr","size":"Medium","type":"Elemental","tags":"","CR":"6","alignment":"true neutral","page":"MM 139"},
	{"name":"Gargoyle","size":"Medium","type":"Elemental","tags":"","CR":"2","alignment":"chaotic evil","page":"MM 140"},
	{"name":"Dao","size":"Large","type":"Elemental","tags":"","CR":"11","alignment":"neutral evil","page":"MM 143"},
	{"name":"Djinni","size":"Large","type":"Elemental","tags":"","CR":"11","alignment":"chaotic good","page":"MM 144"},
	{"name":"Efreeti","size":"Large","type":"Elemental","tags":"","CR":"11","alignment":"lawful evil","page":"MM 145"},
	{"name":"Marid","size":"Large","type":"Elemental","tags":"","CR":"11","alignment":"chaotic neutral","page":"MM 146"},
	{"name":"Ghost","size":"Medium","type":"Undead","tags":"","CR":"4","alignment":"any","page":"MM 147"},
	{"name":"Ghast","size":"Medium","type":"Undead","tags":"","CR":"2","alignment":"chaotic evil","page":"MM 148"},
	{"name":"Ghoul","size":"Medium","type":"Undead","tags":"","CR":"1","alignment":"chaotic evil","page":"MM 148"},
	{"name":"Cloud Giant","size":"Huge","type":"Giant","tags":"","CR":"9","alignment":"neutral good","page":"MM 154"},
	{"name":"Cloud Giant","size":"Huge","type":"Giant","tags":"","CR":"9","alignment":"neutral evil","page":"MM 154"},
	{"name":"Fire Giant","size":"Huge","type":"Giant","tags":"","CR":"9","alignment":"lawful evil","page":"MM 154"},
	{"name":"Frost Giant","size":"Huge","type":"Giant","tags":"","CR":"8","alignment":"neutral evil","page":"MM 155"},
	{"name":"Hill Giant","size":"Huge","type":"Giant","tags":"","CR":"5","alignment":"chaotic evil","page":"MM 155"},
	{"name":"Stone Giant","size":"Huge","type":"Giant","tags":"","CR":"7","alignment":"true neutral","page":"MM 156"},
	{"name":"Storm Giant","size":"Huge","type":"Giant","tags":"","CR":"13","alignment":"chaotic good","page":"MM 156"},
	{"name":"Gibbering Mouther","size":"Medium","type":"Aberration","tags":"","CR":"2","alignment":"true neutral","page":"MM 157"},
	{"name":"Githyanki Knight","size":"Medium","type":"Humanoid","tags":"Gith","CR":"8","alignment":"lawful evil","page":"MM 160"},
	{"name":"Githyanki Warrior","size":"Medium","type":"Humanoid","tags":"Gith","CR":"3","alignment":"lawful evil","page":"MM 160"},
	{"name":"Githzerai Monk","size":"Medium","type":"Humanoid","tags":"Gith","CR":"2","alignment":"lawful neutral","page":"MM 161"},
	{"name":"Githzerai Zerth","size":"Medium","type":"Humanoid","tags":"Gith","CR":"6","alignment":"lawful neutral","page":"MM 161"},
	{"name":"Gnoll","size":"Medium","type":"Humanoid","tags":"Gnoll","CR":"1/2","alignment":"chaotic evil","page":"MM 163"},
	{"name":"Gnoll Fang of Yeenoghu","size":"Medium","type":"Humanoid","tags":"Gnoll","CR":"4","alignment":"chaotic evil","page":"MM 163"},
	{"name":"Gnoll Pack Lord","size":"Medium","type":"Humanoid","tags":"Gnoll","CR":"2","alignment":"chaotic evil","page":"MM 163"},
	{"name":"Gnome, Deep (Svirfneblin)","size":"Small","type":"Humanoid","tags":"Gnome","CR":"1/2","alignment":"neutral good","page":"MM 164"},
	{"name":"Goblin","size":"Small","type":"Humanoid","tags":"Goblinoid","CR":"1/4","alignment":"neutral evil","page":"MM 166"},
	{"name":"Goblin Boss","size":"Small","type":"Humanoid","tags":"Goblinoid","CR":"1","alignment":"neutral evil","page":"MM 166"},
	{"name":"Clay Golem","size":"Large","type":"Construct","tags":"","CR":"9","alignment":"unaligned","page":"MM 168"},
	{"name":"Flesh Golem","size":"Medium","type":"Construct","tags":"","CR":"5","alignment":"true neutral","page":"MM 169"},
	{"name":"Iron Golem","size":"Large","type":"Construct","tags":"","CR":"16","alignment":"unaligned","page":"MM 170"},
	{"name":"Stone Golem","size":"Large","type":"Construct","tags":"","CR":"10","alignment":"unaligned","page":"MM 170"},
	{"name":"Gorgon","size":"Large","type":"Construct","tags":"","CR":"5","alignment":"unaligned","page":"MM 171"},
	{"name":"Grell","size":"Medium","type":"Aberration","tags":"","CR":"3","alignment":"neutral evil","page":"MM 172"},
	{"name":"Grick","size":"Medium","type":"Monstrosity","tags":"","CR":"2","alignment":"true neutral","page":"MM 173"},
	{"name":"Grick Alpha","size":"Large","type":"Monstrosity","tags":"","CR":"7","alignment":"true neutral","page":"MM 173"},
	{"name":"Griffon","size":"Large","type":"Monstrosity","tags":"","CR":"2","alignment":"unaligned","page":"MM 174"},
	{"name":"Grimlock","size":"Medium","type":"Humanoid","tags":"Grimlock","CR":"1/4","alignment":"neutral evil","page":"MM 175"},
	{"name":"Green Hag","size":"Medium","type":"Fey","tags":"","CR":"3","alignment":"neutral evil","page":"MM 177"},
	{"name":"Night Hag","size":"Medium","type":"Fiend","tags":"","CR":"5","alignment":"neutral evil","page":"MM 178"},
	{"name":"Sea Hag","size":"Medium","type":"Fey","tags":"","CR":"2","alignment":"chaotic evil","page":"MM 179"},
	{"name":"Half-Red Dragon Veteran","size":"Medium","type":"Humanoid","tags":"Human","CR":"5","alignment":"any","page":"MM 180"},
	{"name":"Harpy","size":"Medium","type":"Monstrosity","tags":"","CR":"1","alignment":"chaotic evil","page":"MM 181"},
	{"name":"Hell Hound","size":"Medium","type":"Fiend","tags":"","CR":"3","alignment":"lawful evil","page":"MM 182"},
	{"name":"Helmed Horror","size":"Medium","type":"Construct","tags":"","CR":"4","alignment":"true neutral","page":"MM 183"},
	{"name":"Hippogriff","size":"Large","type":"Monstrosity","tags":"","CR":"1","alignment":"unaligned","page":"MM 184"},
	{"name":"Hobgoblin","size":"Medium","type":"Humanoid","tags":"Goblinoid","CR":"1/2","alignment":"lawful evil","page":"MM 186"},
	{"name":"Hobgoblin Captain","size":"Medium","type":"Humanoid","tags":"Goblinoid","CR":"3","alignment":"lawful evil","page":"MM 186"},
	{"name":"Hobgoblin Warlord","size":"Medium","type":"Humanoid","tags":"Goblinoid","CR":"6","alignment":"lawful evil","page":"MM 187"},
	{"name":"Homunculus","size":"Tiny","type":"Construct","tags":"","CR":"0","alignment":"true neutral","page":"MM 188"},
	{"name":"Hook Horror","size":"Large","type":"Monstrosity","tags":"","CR":"3","alignment":"true neutral","page":"MM 189"},
	{"name":"Hydra","size":"Huge","type":"Monstrosity","tags":"","CR":"8","alignment":"unaligned","page":"MM 190"},
	{"name":"Intellect Devourer","size":"Tiny","type":"Aberration","tags":"","CR":"2","alignment":"lawful evil","page":"MM 191"},
	{"name":"Invisible Stalker","size":"Medium","type":"Elemental","tags":"","CR":"6","alignment":"true neutral","page":"MM 192"},
	{"name":"Jackalwere","size":"Medium","type":"Humanoid","tags":"Shapechanger","CR":"1/2","alignment":"chaotic evil","page":"MM 193"},
	{"name":"Kenku","size":"Medium","type":"Humanoid","tags":"Kenku","CR":"1/4","alignment":"chaotic neutral","page":"MM 194"},
	{"name":"Kobold","size":"Small","type":"Humanoid","tags":"Kobold","CR":"1/8","alignment":"lawful evil","page":"MM 195"},
	{"name":"Winged Kobold","size":"Small","type":"Humanoid","tags":"Kobold","CR":"1/4","alignment":"lawful evil","page":"MM 195"},
	{"name":"Kraken","size":"Gargantuan","type":"Monstrosity","tags":"Titan","CR":"23","alignment":"chaotic evil","page":"MM 197"},
	{"name":"Kuo-Toa","size":"Medium","type":"Humanoid","tags":"Kuo-toa","CR":"1/4","alignment":"neutral evil","page":"MM 199"},
	{"name":"Kuo-Toa Archpriest","size":"Medium","type":"Humanoid","tags":"Kuo-toa","CR":"6","alignment":"neutral evil","page":"MM 200"},
	{"name":"Kuo-Toa Whip","size":"Medium","type":"Humanoid","tags":"Kuo-toa","CR":"1","alignment":"neutral evil","page":"MM 200"},
	{"name":"Lamia","size":"Large","type":"Monstrosity","tags":"","CR":"4","alignment":"chaotic evil","page":"MM 201"},
	{"name":"Lich","size":"Medium","type":"Undead","tags":"","CR":"21","alignment":"any evil","page":"MM 202"},
	{"name":"Lizardfolk","size":"Medium","type":"Humanoid","tags":"Lizardfolk","CR":"1/2","alignment":"true neutral","page":"MM 204"},
	{"name":"Lizard King/Queen","size":"Medium","type":"Humanoid","tags":"Lizardfolk","CR":"4","alignment":"chaotic evil","page":"MM 205"},
	{"name":"Lizardfolk Shaman","size":"Medium","type":"Humanoid","tags":"Lizardfolk","CR":"2","alignment":"true neutral","page":"MM 205"},
	{"name":"Werebear","size":"Medium","type":"Humanoid","tags":"Human, Shapechanger","CR":"5","alignment":"neutral good","page":"MM 208"},
	{"name":"Wereboar","size":"Medium","type":"Humanoid","tags":"Human, Shapechanger","CR":"4","alignment":"neutral evil","page":"MM 209"},
	{"name":"Wererat","size":"Medium","type":"Humanoid","tags":"Human, Shapechanger","CR":"2","alignment":"lawful evil","page":"MM 209"},
	{"name":"Weretiger","size":"Medium","type":"Humanoid","tags":"Human, Shapechanger","CR":"4","alignment":"true neutral","page":"MM 210"},
	{"name":"Werewolf","size":"Medium","type":"Humanoid","tags":"Human, Shapechanger","CR":"3","alignment":"chaotic evil","page":"MM 211"},
	{"name":"Magmin","size":"Small","type":"Elemental","tags":"","CR":"1/2","alignment":"chaotic neutral","page":"MM 212"},
	{"name":"Manticore","size":"Large","type":"Monstrosity","tags":"","CR":"3","alignment":"lawful evil","page":"MM 213"},
	{"name":"Medusa","size":"Medium","type":"Monstrosity","tags":"","CR":"6","alignment":"lawful evil","page":"MM 214"},
	{"name":"Dust Mephit","size":"Small","type":"Elemental","tags":"","CR":"1/2","alignment":"neutral evil","page":"MM 215"},
	{"name":"Ice Mephit","size":"Small","type":"Elemental","tags":"","CR":"1/2","alignment":"neutral evil","page":"MM 215"},
	{"name":"Magma Mephit","size":"Small","type":"Elemental","tags":"","CR":"1/2","alignment":"neutral evil","page":"MM 216"},
	{"name":"Mud Mephit","size":"Small","type":"Elemental","tags":"","CR":"1/4","alignment":"neutral evil","page":"MM 216"},
	{"name":"Smoke Mephit","size":"Small","type":"Elemental","tags":"","CR":"1/4","alignment":"neutral evil","page":"MM 217"},
	{"name":"Steam Mephit","size":"Small","type":"Elemental","tags":"","CR":"1/4","alignment":"neutral evil","page":"MM 217"},
	{"name":"Merfolk","size":"Medium","type":"Humanoid","tags":"Merfolk","CR":"1/8","alignment":"true neutral","page":"MM 218"},
	{"name":"Merrow","size":"Large","type":"Monstrosity","tags":"","CR":"2","alignment":"chaotic evil","page":"MM 219"},
	{"name":"Mimic","size":"Medium","type":"Monstrosity","tags":"","CR":"2","alignment":"true neutral","page":"MM 220"},
	{"name":"Mind Flayer","size":"Medium","type":"Aberration","tags":"","CR":"7","alignment":"lawful evil","page":"MM 222"},
	{"name":"Minotaur","size":"Large","type":"Monstrosity","tags":"","CR":"3","alignment":"chaotic evil","page":"MM 223"},
	{"name":"Monodrone","size":"Medium","type":"Construct","tags":"","CR":"1/8","alignment":"lawful neutral","page":"MM 224"},
	{"name":"Duodrone","size":"Medium","type":"Construct","tags":"","CR":"1/4","alignment":"lawful neutral","page":"MM 225"},
	{"name":"Tridrone","size":"Medium","type":"Construct","tags":"","CR":"1/2","alignment":"lawful neutral","page":"MM 225"},
	{"name":"Pentadrone","size":"Large","type":"Construct","tags":"","CR":"2","alignment":"lawful neutral","page":"MM 226"},
	{"name":"Quadrone","size":"Medium","type":"Construct","tags":"","CR":"1","alignment":"lawful neutral","page":"MM 226"},
	{"name":"Mummy","size":"Medium","type":"Undead","tags":"","CR":"3","alignment":"lawful evil","page":"MM 228"},
	{"name":"Mummy Lord","size":"Medium","type":"Undead","tags":"","CR":"15","alignment":"lawful evil","page":"MM 229"},
	{"name":"Myconid Sprout","size":"Small","type":"Plant","tags":"","CR":"0","alignment":"lawful neutral","page":"MM 230"},
	{"name":"Quaggoth Spore Servant","size":"Medium","type":"Plant","tags":"","CR":"1","alignment":"unaligned","page":"MM 230"},
	{"name":"Myconid Adult","size":"Medium","type":"Plant","tags":"","CR":"1/2","alignment":"lawful neutral","page":"MM 232"},
	{"name":"Myconid Sovereign","size":"Large","type":"Plant","tags":"","CR":"2","alignment":"lawful neutral","page":"MM 232"},
	{"name":"Bone Naga","size":"Large","type":"Undead","tags":"","CR":"4","alignment":"lawful evil","page":"MM 233"},
	{"name":"Guardian Naga","size":"Large","type":"Monstrosity","tags":"","CR":"10","alignment":"lawful evil","page":"MM 234"},
	{"name":"Spirit Naga","size":"Large","type":"Monstrosity","tags":"","CR":"8","alignment":"chaotic evil","page":"MM 234"},
	{"name":"Nightmare","size":"Large","type":"Fiend","tags":"","CR":"3","alignment":"neutral evil","page":"MM 235"},
	{"name":"Nothic","size":"Medium","type":"Aberration","tags":"","CR":"2","alignment":"neutral evil","page":"MM 236"},
	{"name":"Ogre","size":"Large","type":"Giant","tags":"","CR":"2","alignment":"chaotic evil","page":"MM 237"},
	{"name":"Half Ogre","size":"Large","type":"Giant","tags":"","CR":"1","alignment":"chaotic any","page":"MM 238"},
	{"name":"Oni","size":"Large","type":"Giant","tags":"","CR":"7","alignment":"lawful evil","page":"MM 239"},
	{"name":"Black Pudding","size":"Large","type":"Ooze","tags":"","CR":"4","alignment":"unaligned","page":"MM 241"},
	{"name":"Gelatinous Cube","size":"Large","type":"Ooze","tags":"","CR":"2","alignment":"unaligned","page":"MM 242"},
	{"name":"Gray Ooze","size":"Medium","type":"Ooze","tags":"","CR":"1/2","alignment":"unaligned","page":"MM 243"},
	{"name":"Ochre Jelly","size":"Large","type":"Ooze","tags":"","CR":"2","alignment":"unaligned","page":"MM 243"},
	{"name":"Orc","size":"Medium","type":"Humanoid","tags":"Orc","CR":"1/2","alignment":"chaotic evil","page":"MM 246"},
	{"name":"Orc War Chief","size":"Medium","type":"Humanoid","tags":"Orc","CR":"4","alignment":"chaotic evil","page":"MM 246"},
	{"name":"Orc Eye of Gruumsh","size":"Medium","type":"Humanoid","tags":"Orc","CR":"2","alignment":"chaotic evil","page":"MM 247"},
	{"name":"Orog","size":"Medium","type":"Humanoid","tags":"Orc","CR":"2","alignment":"chaotic evil","page":"MM 247"},
	{"name":"Otyugh","size":"Large","type":"Aberration","tags":"","CR":"5","alignment":"true neutral","page":"MM 248"},
	{"name":"Owlbear","size":"Large","type":"Monstrosity","tags":"","CR":"3","alignment":"unaligned","page":"MM 249"},
	{"name":"Pegasus","size":"Large","type":"Celestial","tags":"","CR":"2","alignment":"chaotic good","page":"MM 250"},
	{"name":"Peryton","size":"Medium","type":"Monstrosity","tags":"","CR":"2","alignment":"chaotic evil","page":"MM 251"},
	{"name":"Piercer","size":"Medium","type":"Monstrosity","tags":"","CR":"1/2","alignment":"unaligned","page":"MM 252"},
	{"name":"Pixie","size":"Tiny","type":"Fey","tags":"","CR":"1/4","alignment":"neutral good","page":"MM 253"},
	{"name":"Pseudodragon","size":"Tiny","type":"Dragon","tags":"","CR":"1/4","alignment":"neutral good","page":"MM 254"},
	{"name":"Purple Worm","size":"Gargantuan","type":"Monstrosity","tags":"","CR":"15","alignment":"unaligned","page":"MM 255"},
	{"name":"Quaggoth","size":"Medium","type":"Humanoid","tags":"Quaggoth","CR":"2","alignment":"chaotic neutral","page":"MM 256"},
	{"name":"Rakshasa","size":"Medium","type":"Fiend","tags":"","CR":"13","alignment":"lawful evil","page":"MM 257"},
	{"name":"Remorhaz","size":"Huge","type":"Monstrosity","tags":"","CR":"11","alignment":"unaligned","page":"MM 258"},
	{"name":"Young Remorhaz","size":"Large","type":"Monstrosity","tags":"","CR":"5","alignment":"unaligned","page":"MM 258"},
	{"name":"Revenant","size":"Medium","type":"Undead","tags":"","CR":"5","alignment":"true neutral","page":"MM 259"},
	{"name":"Roc","size":"Gargantuan","type":"Monstrosity","tags":"","CR":"11","alignment":"unaligned","page":"MM 260"},
	{"name":"Roper","size":"Large","type":"Monstrosity","tags":"","CR":"5","alignment":"neutral evil","page":"MM 261"},
	{"name":"Rust Monster","size":"Medium","type":"Monstrosity","tags":"","CR":"1/2","alignment":"unaligned","page":"MM 262"},
	{"name":"Sahuagin","size":"Medium","type":"Humanoid","tags":"Sahuagin","CR":"1/2","alignment":"lawful evil","page":"MM 263"},
	{"name":"Sahuagin Baron","size":"Large","type":"Humanoid","tags":"Sahuagin","CR":"5","alignment":"lawful evil","page":"MM 264"},
	{"name":"Sahuagin Priestess","size":"Medium","type":"Humanoid","tags":"Sahuagin","CR":"2","alignment":"lawful evil","page":"MM 264"},
	{"name":"Fire Snake","size":"Medium","type":"Elemental","tags":"","CR":"1","alignment":"neutral evil","page":"MM 265"},
	{"name":"Salamander","size":"Large","type":"Elemental","tags":"","CR":"5","alignment":"neutral evil","page":"MM 266"},
	{"name":"Satyr","size":"Medium","type":"Fey","tags":"","CR":"1/2","alignment":"chaotic neutral","page":"MM 267"},
	{"name":"Scarecrow","size":"Medium","type":"Construct","tags":"","CR":"1","alignment":"chaotic evil","page":"MM 268"},
	{"name":"Shadow","size":"Medium","type":"Undead","tags":"","CR":"1/2","alignment":"chaotic evil","page":"MM 269"},
	{"name":"Shambling Mound","size":"Large","type":"Plant","tags":"","CR":"5","alignment":"unaligned","page":"MM 270"},
	{"name":"Shield Guardian","size":"Large","type":"Construct","tags":"","CR":"7","alignment":"unaligned","page":"MM 271"},
	{"name":"Skeleton","size":"Medium","type":"Undead","tags":"","CR":"1/4","alignment":"lawful evil","page":"MM 272"},
	{"name":"Minotaur Skeleton","size":"Large","type":"Undead","tags":"","CR":"2","alignment":"lawful evil","page":"MM 273"},
	{"name":"Warhorse Skeleton","size":"Large","type":"Undead","tags":"","CR":"1/2","alignment":"lawful evil","page":"MM 273"},
	{"name":"Blue Slaad","size":"Large","type":"Aberration","tags":"","CR":"7","alignment":"chaotic neutral","page":"MM 276"},
	{"name":"Red Slaad","size":"Large","type":"Aberration","tags":"","CR":"5","alignment":"chaotic neutral","page":"MM 276"},
	{"name":"Slaad Tadpole","size":"Tiny","type":"Aberration","tags":"","CR":"1/8","alignment":"chaotic neutral","page":"MM 276"},
	{"name":"Gray Slaad","size":"Medium","type":"Aberration","tags":"","CR":"9","alignment":"chaotic neutral","page":"MM 277"},
	{"name":"Green Slaad","size":"Large","type":"Aberration","tags":"","CR":"8","alignment":"chaotic neutral","page":"MM 277"},
	{"name":"Death Slaad","size":"Medium","type":"Aberration","tags":"","CR":"10","alignment":"chaotic evil","page":"MM 278"},
	{"name":"Specter","size":"Medium","type":"Undead","tags":"","CR":"1","alignment":"chaotic evil","page":"MM 279"},
	{"name":"Androsphinx","size":"Large","type":"Monstrosity","tags":"","CR":"17","alignment":"lawful neutral","page":"MM 281"},
	{"name":"Gynosphinx","size":"Large","type":"Monstrosity","tags":"","CR":"11","alignment":"lawful neutral","page":"MM 282"},
	{"name":"Sprite","size":"Tiny","type":"Fey","tags":"","CR":"1/4","alignment":"neutral good","page":"MM 283"},
	{"name":"Stirge","size":"Tiny","type":"Beast","tags":"","CR":"1/8","alignment":"unaligned","page":"MM 284"},
	{"name":"Succubus/Incubus","size":"Medium","type":"Fiend","tags":"Shapechanger","CR":"4","alignment":"neutral evil","page":"MM 285"},
	{"name":"Tarrasque","size":"Gargantuan","type":"Monstrosity","tags":"Titan","CR":"30","alignment":"unaligned","page":"MM 286"},
	{"name":"Thri-Kreen","size":"Medium","type":"Humanoid","tags":"Thri-kreen","CR":"1","alignment":"chaotic neutral","page":"MM 288"},
	{"name":"Treant","size":"Huge","type":"Plant","tags":"","CR":"9","alignment":"chaotic good","page":"MM 289"},
	{"name":"Troglodyte","size":"Medium","type":"Humanoid","tags":"Troglodyte","CR":"1/4","alignment":"chaotic evil","page":"MM 290"},
	{"name":"Troll","size":"Large","type":"Giant","tags":"","CR":"5","alignment":"chaotic evil","page":"MM 291"},
	{"name":"Umber Hulk","size":"Large","type":"Monstrosity","tags":"","CR":"5","alignment":"chaotic evil","page":"MM 292"},
	{"name":"Unicorn","size":"Large","type":"Celestial","tags":"","CR":"5","alignment":"lawful good","page":"MM 294"},
	{"name":"Vampire","size":"Medium","type":"Undead","tags":"Shapechanger","CR":"13","alignment":"lawful evil","page":"MM 297"},
	{"name":"Vampire Spawn","size":"Medium","type":"Undead","tags":"","CR":"5","alignment":"neutral evil","page":"MM 298"},
	{"name":"Water Weird","size":"Large","type":"Elemental","tags":"","CR":"3","alignment":"true neutral","page":"MM 299"},
	{"name":"Wight","size":"Medium","type":"Undead","tags":"","CR":"3","alignment":"neutral evil","page":"MM 300"},
	{"name":"Will-O'-Wisp","size":"Tiny","type":"Undead","tags":"","CR":"2","alignment":"chaotic evil","page":"MM 301"},
	{"name":"Wraith","size":"Medium","type":"Undead","tags":"","CR":"5","alignment":"neutral evil","page":"MM 302"},
	{"name":"Wyvern","size":"Large","type":"Dragon","tags":"","CR":"6","alignment":"unaligned","page":"MM 303"},
	{"name":"Xorn","size":"Medium","type":"Elemental","tags":"","CR":"5","alignment":"true neutral","page":"MM 304"},
	{"name":"Yeti","size":"Large","type":"Monstrosity","tags":"","CR":"3","alignment":"chaotic evil","page":"MM 305"},
	{"name":"Abominable Yeti","size":"Huge","type":"Monstrosity","tags":"","CR":"9","alignment":"chaotic evil","page":"MM 306"},
	{"name":"Yuan-Ti Abomination","size":"Large","type":"Monstrosity","tags":"Shapechanger, Yuan-ti","CR":"7","alignment":"neutral evil","page":"MM 308"},
	{"name":"Yuan-Ti Malison","size":"Medium","type":"Monstrosity","tags":"Shapechanger, Yuan-ti","CR":"3","alignment":"neutral evil","page":"MM 309"},
	{"name":"Yuan-Ti Pureblood","size":"Medium","type":"Monstrosity","tags":"Yuan-ti","CR":"1","alignment":"neutral evil","page":"MM 310"},
	{"name":"Arcanaloth","size":"Medium","type":"Fiend","tags":"Yugoloth","CR":"12","alignment":"neutral evil","page":"MM 313"},
	{"name":"Mezzoloth","size":"Medium","type":"Fiend","tags":"Yugoloth","CR":"5","alignment":"neutral evil","page":"MM 313"},
	{"name":"Nycaloth","size":"Large","type":"Fiend","tags":"Yugoloth","CR":"9","alignment":"neutral evil","page":"MM 314"},
	{"name":"Ultroloth","size":"Medium","type":"Fiend","tags":"Yugoloth","CR":"13","alignment":"neutral evil","page":"MM 314"},
	{"name":"Beholder Zombie","size":"Large","type":"Undead","tags":"","CR":"5","alignment":"neutral evil","page":"MM 316"},
	{"name":"Ogre Zombie","size":"Large","type":"Undead","tags":"","CR":"2","alignment":"neutral evil","page":"MM 316"},
	{"name":"Zombie","size":"Medium","type":"Undead","tags":"","CR":"1/4","alignment":"neutral evil","page":"MM 316"},
	{"name":"Ape","size":"Medium","type":"Beast","tags":"","CR":"1/2","alignment":"unaligned","page":"MM 317"},
	{"name":"Awakened Shrub","size":"Small","type":"Plant","tags":"","CR":"0","alignment":"unaligned","page":"MM 317"},
	{"name":"Awakened Tree","size":"Huge","type":"Plant","tags":"","CR":"2","alignment":"unaligned","page":"MM 317"},
	{"name":"Axe Beak","size":"Large","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 317"},
	{"name":"Baboon","size":"Small","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 318"},
	{"name":"Badger","size":"Tiny","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 318"},
	{"name":"Bat","size":"Tiny","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 318"},
	{"name":"Black Bear","size":"Medium","type":"Beast","tags":"","CR":"1/2","alignment":"unaligned","page":"MM 318"},
	{"name":"Blink Dog","size":"Medium","type":"Fey","tags":"","CR":"1/4","alignment":"lawful good","page":"MM 318"},
	{"name":"Blood Hawk","size":"Small","type":"Beast","tags":"","CR":"1/8","alignment":"unaligned","page":"MM 319"},
	{"name":"Boar","size":"Medium","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 319"},
	{"name":"Brown Bear","size":"Large","type":"Beast","tags":"","CR":"1","alignment":"unaligned","page":"MM 319"},
	{"name":"Camel","size":"Large","type":"Beast","tags":"","CR":"1/8","alignment":"unaligned","page":"MM 320"},
	{"name":"Cat","size":"Tiny","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 320"},
	{"name":"Constrictor Snake","size":"Large","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 320"},
	{"name":"Crab","size":"Tiny","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 320"},
	{"name":"Crocodile","size":"Large","type":"Beast","tags":"","CR":"1/2","alignment":"unaligned","page":"MM 320"},
	{"name":"Death Dog","size":"Medium","type":"Monstrosity","tags":"","CR":"1","alignment":"neutral evil","page":"MM 321"},
	{"name":"Deer","size":"Medium","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 321"},
	{"name":"Dire Wolf","size":"Large","type":"Beast","tags":"","CR":"1","alignment":"unaligned","page":"MM 321"},
	{"name":"Draft Horse","size":"Large","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 321"},
	{"name":"Eagle","size":"Small","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 322"},
	{"name":"Elephant","size":"Huge","type":"Beast","tags":"","CR":"4","alignment":"unaligned","page":"MM 322"},
	{"name":"Elk","size":"Large","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 322"},
	{"name":"Flying Snake","size":"Tiny","type":"Beast","tags":"","CR":"1/8","alignment":"unaligned","page":"MM 322"},
	{"name":"Frog","size":"Tiny","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 322"},
	{"name":"Giant Ape","size":"Huge","type":"Beast","tags":"","CR":"7","alignment":"unaligned","page":"MM 323"},
	{"name":"Giant Badger","size":"Medium","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 323"},
	{"name":"Giant Bat","size":"Large","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 323"},
	{"name":"Giant Boar","size":"Large","type":"Beast","tags":"","CR":"2","alignment":"unaligned","page":"MM 323"},
	{"name":"Giant Centipede","size":"Small","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 323"},
	{"name":"Giant Constrictor Snake","size":"Huge","type":"Beast","tags":"","CR":"2","alignment":"unaligned","page":"MM 324"},
	{"name":"Giant Crab","size":"Medium","type":"Beast","tags":"","CR":"1/8","alignment":"unaligned","page":"MM 324"},
	{"name":"Giant Crocodile","size":"Huge","type":"Beast","tags":"","CR":"5","alignment":"unaligned","page":"MM 324"},
	{"name":"Giant Eagle","size":"Large","type":"Beast","tags":"","CR":"1","alignment":"neutral good","page":"MM 324"},
	{"name":"Giant Elk","size":"Huge","type":"Beast","tags":"","CR":"2","alignment":"unaligned","page":"MM 325"},
	{"name":"Giant Fire Beetle","size":"Small","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 325"},
	{"name":"Giant Frog","size":"Medium","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 325"},
	{"name":"Giant Goat","size":"Large","type":"Beast","tags":"","CR":"1/2","alignment":"unaligned","page":"MM 326"},
	{"name":"Giant Hyena","size":"Large","type":"Beast","tags":"","CR":"1","alignment":"unaligned","page":"MM 326"},
	{"name":"Giant Lizard","size":"Large","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 326"},
	{"name":"Giant Octopus","size":"Large","type":"Beast","tags":"","CR":"1","alignment":"unaligned","page":"MM 326"},
	{"name":"Giant Owl","size":"Large","type":"Beast","tags":"","CR":"1/4","alignment":"true neutral","page":"MM 327"},
	{"name":"Giant Poisonous Snake","size":"Medium","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 327"},
	{"name":"Giant Rat","size":"Small","type":"Beast","tags":"","CR":"1/8","alignment":"unaligned","page":"MM 327"},
	{"name":"Giant Scorpion","size":"Large","type":"Beast","tags":"","CR":"3","alignment":"unaligned","page":"MM 327"},
	{"name":"Giant Sea Horse","size":"Large","type":"Beast","tags":"","CR":"1/2","alignment":"unaligned","page":"MM 328"},
	{"name":"Giant Shark","size":"Huge","type":"Beast","tags":"","CR":"5","alignment":"unaligned","page":"MM 328"},
	{"name":"Giant Spider","size":"Large","type":"Beast","tags":"","CR":"1","alignment":"unaligned","page":"MM 328"},
	{"name":"Giant Toad","size":"Large","type":"Beast","tags":"","CR":"1","alignment":"unaligned","page":"MM 329"},
	{"name":"Giant Vulture","size":"Large","type":"Beast","tags":"","CR":"1","alignment":"neutral evil","page":"MM 329"},
	{"name":"Giant Wasp","size":"Medium","type":"Beast","tags":"","CR":"1/2","alignment":"unaligned","page":"MM 329"},
	{"name":"Giant Weasel","size":"Medium","type":"Beast","tags":"","CR":"1/8","alignment":"unaligned","page":"MM 329"},
	{"name":"Giant Wolf Spider","size":"Medium","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 330"},
	{"name":"Goat","size":"Medium","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 330"},
	{"name":"Hawk","size":"Tiny","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 330"},
	{"name":"Hunter Shark","size":"Large","type":"Beast","tags":"","CR":"2","alignment":"unaligned","page":"MM 330"},
	{"name":"Hyena","size":"Medium","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 331"},
	{"name":"Jackal","size":"Small","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 331"},
	{"name":"Killer Whale","size":"Huge","type":"Beast","tags":"","CR":"3","alignment":"unaligned","page":"MM 331"},
	{"name":"Lion","size":"Large","type":"Beast","tags":"","CR":"1","alignment":"unaligned","page":"MM 331"},
	{"name":"Lizard","size":"Tiny","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 332"},
	{"name":"Mammoth","size":"Huge","type":"Beast","tags":"","CR":"6","alignment":"unaligned","page":"MM 332"},
	{"name":"Mastiff","size":"Medium","type":"Beast","tags":"","CR":"1/8","alignment":"unaligned","page":"MM 332"},
	{"name":"Mule","size":"Medium","type":"Beast","tags":"","CR":"1/8","alignment":"unaligned","page":"MM 333"},
	{"name":"Octopus","size":"Small","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 333"},
	{"name":"Owl","size":"Tiny","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 333"},
	{"name":"Panther","size":"Medium","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 333"},
	{"name":"Phase Spider","size":"Large","type":"Monstrosity","tags":"","CR":"3","alignment":"unaligned","page":"MM 334"},
	{"name":"Poisonous Snake","size":"Tiny","type":"Beast","tags":"","CR":"1/8","alignment":"unaligned","page":"MM 334"},
	{"name":"Polar Bear","size":"Large","type":"Beast","tags":"","CR":"2","alignment":"unaligned","page":"MM 334"},
	{"name":"Pony","size":"Medium","type":"Beast","tags":"","CR":"1/8","alignment":"unaligned","page":"MM 335"},
	{"name":"Quipper","size":"Tiny","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 335"},
	{"name":"Rat","size":"Tiny","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 335"},
	{"name":"Raven","size":"Tiny","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 335"},
	{"name":"Reef Shark","size":"Medium","type":"Beast","tags":"","CR":"1/2","alignment":"unaligned","page":"MM 336"},
	{"name":"Rhinoceros","size":"Large","type":"Beast","tags":"","CR":"2","alignment":"unaligned","page":"MM 336"},
	{"name":"Riding Horse","size":"Large","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 336"},
	{"name":"Saber-Toothed Tiger","size":"Large","type":"Beast","tags":"","CR":"2","alignment":"unaligned","page":"MM 336"},
	{"name":"Scorpion","size":"Tiny","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 337"},
	{"name":"Sea Horse","size":"Tiny","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 337"},
	{"name":"Spider","size":"Tiny","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 337"},
	{"name":"Swarm of Bats","size":"Medium","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 337"},
	{"name":"Swarm of Insects","size":"Medium","type":"Beast","tags":"","CR":"1/2","alignment":"unaligned","page":"MM 338"},
	{"name":"Swarm of Poisonous Snakes","size":"Medium","type":"Beast","tags":"","CR":"2","alignment":"unaligned","page":"MM 338"},
	{"name":"Swarm of Quippers","size":"Medium","type":"Beast","tags":"","CR":"1","alignment":"unaligned","page":"MM 338"},
	{"name":"Swarm of Rats","size":"Medium","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 339"},
	{"name":"Swarm of Ravens","size":"Medium","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 339"},
	{"name":"Tiger","size":"Large","type":"Beast","tags":"","CR":"1","alignment":"unaligned","page":"MM 339"},
	{"name":"Vulture","size":"Medium","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 339"},
	{"name":"Warhorse","size":"Large","type":"Beast","tags":"","CR":"1/2","alignment":"unaligned","page":"MM 340"},
	{"name":"Weasel","size":"Tiny","type":"Beast","tags":"","CR":"0","alignment":"unaligned","page":"MM 340"},
	{"name":"Winter Wolf","size":"Large","type":"Monstrosity","tags":"","CR":"3","alignment":"neutral evil","page":"MM 340"},
	{"name":"Wolf","size":"Medium","type":"Beast","tags":"","CR":"1/4","alignment":"unaligned","page":"MM 341"},
	{"name":"Worg","size":"Large","type":"Monstrosity","tags":"","CR":"1/2","alignment":"neutral evil","page":"MM 341"},
	{"name":"Acolyte","size":"Medium","type":"Humanoid","tags":"NPC","CR":"1/4","alignment":"any","page":"MM 342"},
	{"name":"Archmage","size":"Medium","type":"Humanoid","tags":"NPC","CR":"12","alignment":"any","page":"MM 342"},
	{"name":"Assassin","size":"Medium","type":"Humanoid","tags":"NPC","CR":"8","alignment":"any","page":"MM 343"},
	{"name":"Bandit","size":"Medium","type":"Humanoid","tags":"NPC","CR":"1/8","alignment":"any","page":"MM 343"},
	{"name":"Bandit Captain","size":"Medium","type":"Humanoid","tags":"NPC","CR":"2","alignment":"any","page":"MM 344"},
	{"name":"Berserker","size":"Medium","type":"Humanoid","tags":"NPC","CR":"2","alignment":"chaotic any","page":"MM 344"},
	{"name":"Commoner","size":"Medium","type":"Humanoid","tags":"NPC","CR":"0","alignment":"any","page":"MM 345"},
	{"name":"Cult Fanatic","size":"Medium","type":"Humanoid","tags":"NPC","CR":"2","alignment":"any","page":"MM 345"},
	{"name":"Cultist","size":"Medium","type":"Humanoid","tags":"NPC","CR":"1/8","alignment":"any","page":"MM 345"},
	{"name":"Druid","size":"Medium","type":"Humanoid","tags":"NPC","CR":"2","alignment":"any","page":"MM 346"},
	{"name":"Gladiator","size":"Medium","type":"Humanoid","tags":"NPC","CR":"5","alignment":"any","page":"MM 346"},
	{"name":"Guard","size":"Medium","type":"Humanoid","tags":"NPC","CR":"1/8","alignment":"any","page":"MM 347"},
	{"name":"Knight","size":"Medium","type":"Humanoid","tags":"NPC","CR":"3","alignment":"any","page":"MM 347"},
	{"name":"Mage","size":"Medium","type":"Humanoid","tags":"NPC","CR":"6","alignment":"any","page":"MM 347"},
	{"name":"Noble","size":"Medium","type":"Humanoid","tags":"NPC","CR":"1/8","alignment":"any","page":"MM 348"},
	{"name":"Priest","size":"Medium","type":"Humanoid","tags":"NPC","CR":"2","alignment":"any","page":"MM 348"},
	{"name":"Scout","size":"Medium","type":"Humanoid","tags":"NPC","CR":"1/2","alignment":"any","page":"MM 349"},
	{"name":"Spy","size":"Medium","type":"Humanoid","tags":"NPC","CR":"1","alignment":"any","page":"MM 349"},
	{"name":"Thug","size":"Medium","type":"Humanoid","tags":"NPC","CR":"1/2","alignment":"any","page":"MM 350"},
	{"name":"Tribal Warrior","size":"Medium","type":"Humanoid","tags":"NPC","CR":"1/8","alignment":"any","page":"MM 350"},
	{"name":"Veteran","size":"Medium","type":"Humanoid","tags":"NPC","CR":"3","alignment":"any","page":"MM 350"}
];
